### ISSUE TITLE
Using a session name that is a prefix of the first window results in missing windows

### ISSUE THREAD

**Issue by taDachs** [fmauch/catmux#37]
I have to following catmux config:

```yaml
---
common:
  before_commands: []
parameters: {}

windows:
  - name: perception_base
    layout: tiled # One can use the default layouts specified by tmux
    splits:
      - commands:
        - echo "lala"
  - name: lane_detection
    layout: tiled # One can use the default layouts specified by tmux
    splits:
      - commands:
        - echo "lblb"
``` 

starting it via `catmux_create_session test_config.yaml` works as expected with 2 windows being created. 
If I use the `--session_name` with a name that is a prefix of the first window defined, the window appears to not be created.

For example `catmux_create_session test_config.yaml --session_name perception` creates only one window, but executes the commands from both `perception_base` and `lane_detection` in the same window.

It prints the following error message:

```
Parameters found in session config:
 -
{'before_commands': [], 'name': 'perception_base', 'layout': 'tiled', 'splits': [{'commands': ['echo "lala"']}]}
[{'commands': ['echo "lala"']}]
{'before_commands': [], 'name': 'lane_detection', 'layout': 'tiled', 'splits': [{'commands': ['echo "lblb"']}]}
[{'commands': ['echo "lblb"']}]
no server running on /tmp/tmux-1000/catmux
Using tmux config file: /home/max/.tmux.conf
tmux -L catmux -f /home/max/.tmux.conf new-session -s perception -d
Created session "perception"
create window failed: index 1 in use
Error while calling "%s" ['tmux', '-L', 'catmux', 'new-window', '-t', 'perception']
```

using a session name that is not a prefix of the first window name (for example `perception123` or `lane`) resolves the issue.
